# Generated by Django 5.2.6 on 2025-09-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_items_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('update', 'Update'), ('exclusive', 'Exclusive'), ('match', 'Match'), ('rumor', 'Rumor'), ('analysis', 'Analysis'), ('training', 'Training'), ('special', 'Special'), ('national', 'National'), ('classic', 'Classic'), ('derby', 'Derby')], default='other', max_length=20),
        ),
    ]
