# Generated by Django 5.2.6 on 2025-10-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_items_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.URLField(blank=True, null=True),
        ),
    ]
