# Generated by Django 5.2.6 on 2025-10-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_products_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='thumbnail',
            new_name='thumbnail1',
        ),
        migrations.AddField(
            model_name='products',
            name='thumbnail2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='thumbnail3',
            field=models.URLField(blank=True, null=True),
        ),
    ]
