# Generated by Django 5.2.6 on 2025-10-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_thumbnail_products_thumbnail1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='brandName',
            field=models.CharField(default='brand', max_length=20),
        ),
    ]
